// Default food database - generated from "Keto Grocery & Macro Guide.xlsx"
// All macro values are per 100 g (or 100 ml for beverages).
const DEFAULT_CATEGORIES = ["Meat", "Seafood", "Eggs & Dairy", "Vegetables", "Fruits", "Nuts & Seeds", "Fats & Oils", "Beverages", "Condiments & Sweeteners", "Pantry & Baking", "Snacks"];

const DEFAULT_FOODS = [
 {
  "id": "f1",
  "name": "Ground beef 95/5 (extra lean)",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 131.0,
  "protein": 21.4,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 5.0,
  "rating": "Free"
 },
 {
  "id": "f2",
  "name": "Ground beef 90/10 (lean)",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 176.0,
  "protein": 20.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 10.0,
  "rating": "Free"
 },
 {
  "id": "f3",
  "name": "Ground beef 85/15",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 215.0,
  "protein": 18.6,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 15.0,
  "rating": "Free"
 },
 {
  "id": "f4",
  "name": "Ground beef 80/20 (regular)",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 254.0,
  "protein": 17.2,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 20.0,
  "rating": "Free"
 },
 {
  "id": "f5",
  "name": "Ground beef 73/27 (high fat)",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 332.0,
  "protein": 14.4,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 30.0,
  "rating": "Free"
 },
 {
  "id": "f6",
  "name": "Ribeye steak",
  "brand": "",
  "category": "Meat",
  "notes": "Raw, lean + fat",
  "calories": 274.0,
  "protein": 17.5,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 22.0,
  "rating": "Free"
 },
 {
  "id": "f7",
  "name": "Sirloin steak (top)",
  "brand": "",
  "category": "Meat",
  "notes": "Raw, lean + fat",
  "calories": 201.0,
  "protein": 19.6,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 13.1,
  "rating": "Free"
 },
 {
  "id": "f8",
  "name": "Beef tenderloin (filet)",
  "brand": "",
  "category": "Meat",
  "notes": "Raw, lean + fat",
  "calories": 218.0,
  "protein": 19.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 15.3,
  "rating": "Free"
 },
 {
  "id": "f9",
  "name": "Chuck roast",
  "brand": "",
  "category": "Meat",
  "notes": "Raw, lean + fat",
  "calories": 244.0,
  "protein": 17.4,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 18.9,
  "rating": "Free"
 },
 {
  "id": "f10",
  "name": "Beef brisket",
  "brand": "",
  "category": "Meat",
  "notes": "Raw, whole, lean + fat",
  "calories": 291.0,
  "protein": 16.2,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 24.4,
  "rating": "Free"
 },
 {
  "id": "f11",
  "name": "Beef liver",
  "brand": "",
  "category": "Meat",
  "notes": "Raw; nutrient-dense organ meat",
  "calories": 135.0,
  "protein": 20.4,
  "totalCarbs": 3.9,
  "fiber": 0.0,
  "netCarbs": 3.9,
  "fat": 3.6,
  "rating": "Great"
 },
 {
  "id": "f12",
  "name": "Pork loin chop, boneless",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 144.0,
  "protein": 21.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 6.2,
  "rating": "Free"
 },
 {
  "id": "f13",
  "name": "Pork tenderloin",
  "brand": "",
  "category": "Meat",
  "notes": "Raw, very lean",
  "calories": 120.0,
  "protein": 20.7,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 3.5,
  "rating": "Free"
 },
 {
  "id": "f14",
  "name": "Pork shoulder (butt)",
  "brand": "",
  "category": "Meat",
  "notes": "Raw, lean + fat",
  "calories": 236.0,
  "protein": 17.2,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 18.0,
  "rating": "Free"
 },
 {
  "id": "f15",
  "name": "Pork belly",
  "brand": "",
  "category": "Meat",
  "notes": "Raw; highest-fat cut",
  "calories": 518.0,
  "protein": 9.3,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 53.0,
  "rating": "Free"
 },
 {
  "id": "f16",
  "name": "Bacon",
  "brand": "",
  "category": "Meat",
  "notes": "Pan-fried; check label for added sugar",
  "calories": 541.0,
  "protein": 37.0,
  "totalCarbs": 1.4,
  "fiber": 0.0,
  "netCarbs": 1.4,
  "fat": 41.8,
  "rating": "Free"
 },
 {
  "id": "f17",
  "name": "Ham, deli sliced",
  "brand": "",
  "category": "Meat",
  "notes": "Check label - some brands add sugar",
  "calories": 130.0,
  "protein": 18.0,
  "totalCarbs": 1.5,
  "fiber": 0.0,
  "netCarbs": 1.5,
  "fat": 5.5,
  "rating": "Free"
 },
 {
  "id": "f18",
  "name": "Chicken breast, skinless",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 120.0,
  "protein": 22.5,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 2.6,
  "rating": "Free"
 },
 {
  "id": "f19",
  "name": "Chicken thigh, boneless skinless",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 145.0,
  "protein": 18.6,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 8.0,
  "rating": "Free"
 },
 {
  "id": "f20",
  "name": "Chicken thigh, with skin",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 221.0,
  "protein": 16.5,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 17.0,
  "rating": "Free"
 },
 {
  "id": "f21",
  "name": "Chicken drumstick, with skin",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 161.0,
  "protein": 18.1,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 9.9,
  "rating": "Free"
 },
 {
  "id": "f22",
  "name": "Chicken wings, with skin",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 222.0,
  "protein": 18.3,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 16.2,
  "rating": "Free"
 },
 {
  "id": "f23",
  "name": "Turkey breast, skinless",
  "brand": "",
  "category": "Meat",
  "notes": "Raw, very lean",
  "calories": 104.0,
  "protein": 23.7,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 1.0,
  "rating": "Free"
 },
 {
  "id": "f24",
  "name": "Ground turkey 93/7",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 150.0,
  "protein": 18.7,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 8.0,
  "rating": "Free"
 },
 {
  "id": "f25",
  "name": "Lamb leg / chop",
  "brand": "",
  "category": "Meat",
  "notes": "Raw, lean + fat",
  "calories": 230.0,
  "protein": 17.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 17.5,
  "rating": "Free"
 },
 {
  "id": "f26",
  "name": "Duck breast, skinless",
  "brand": "",
  "category": "Meat",
  "notes": "Raw",
  "calories": 135.0,
  "protein": 18.3,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 5.9,
  "rating": "Free"
 },
 {
  "id": "f27",
  "name": "Duck, with skin",
  "brand": "",
  "category": "Meat",
  "notes": "Raw; very high fat",
  "calories": 404.0,
  "protein": 11.5,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 39.3,
  "rating": "Free"
 },
 {
  "id": "f28",
  "name": "Veal",
  "brand": "",
  "category": "Meat",
  "notes": "Raw, average of cuts",
  "calories": 144.0,
  "protein": 19.4,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 6.8,
  "rating": "Free"
 },
 {
  "id": "f29",
  "name": "Venison",
  "brand": "",
  "category": "Meat",
  "notes": "Raw, very lean game meat",
  "calories": 120.0,
  "protein": 23.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 2.4,
  "rating": "Free"
 },
 {
  "id": "f30",
  "name": "Pepperoni / salami",
  "brand": "",
  "category": "Meat",
  "notes": "Check label; avoid added dextrose",
  "calories": 460.0,
  "protein": 20.0,
  "totalCarbs": 1.5,
  "fiber": 0.0,
  "netCarbs": 1.5,
  "fat": 41.0,
  "rating": "Free"
 },
 {
  "id": "f31",
  "name": "Salmon, Atlantic farmed",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw; high omega-3",
  "calories": 208.0,
  "protein": 20.4,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 13.4,
  "rating": "Free"
 },
 {
  "id": "f32",
  "name": "Salmon, wild",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw; leaner than farmed",
  "calories": 142.0,
  "protein": 19.8,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 6.3,
  "rating": "Free"
 },
 {
  "id": "f33",
  "name": "Tuna, yellowfin",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw",
  "calories": 109.0,
  "protein": 24.4,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 0.5,
  "rating": "Free"
 },
 {
  "id": "f34",
  "name": "Tuna, canned light in water",
  "brand": "",
  "category": "Seafood",
  "notes": "Drained",
  "calories": 86.0,
  "protein": 19.4,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 1.0,
  "rating": "Free"
 },
 {
  "id": "f35",
  "name": "Sardines, canned in oil",
  "brand": "",
  "category": "Seafood",
  "notes": "Drained; with bones = calcium",
  "calories": 208.0,
  "protein": 24.6,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 11.4,
  "rating": "Free"
 },
 {
  "id": "f36",
  "name": "Anchovies, canned in oil",
  "brand": "",
  "category": "Seafood",
  "notes": "Drained; salty - use as flavoring",
  "calories": 210.0,
  "protein": 28.9,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 9.7,
  "rating": "Free"
 },
 {
  "id": "f37",
  "name": "Mackerel, Atlantic",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw; very high omega-3",
  "calories": 205.0,
  "protein": 18.6,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 13.9,
  "rating": "Free"
 },
 {
  "id": "f38",
  "name": "Herring",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw",
  "calories": 158.0,
  "protein": 18.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 9.0,
  "rating": "Free"
 },
 {
  "id": "f39",
  "name": "Trout, rainbow",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw",
  "calories": 141.0,
  "protein": 19.9,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 6.2,
  "rating": "Free"
 },
 {
  "id": "f40",
  "name": "Cod",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw, very lean",
  "calories": 82.0,
  "protein": 17.8,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 0.7,
  "rating": "Free"
 },
 {
  "id": "f41",
  "name": "Halibut",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw",
  "calories": 91.0,
  "protein": 18.6,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 1.3,
  "rating": "Free"
 },
 {
  "id": "f42",
  "name": "Sea bass",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw",
  "calories": 97.0,
  "protein": 18.4,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 2.0,
  "rating": "Free"
 },
 {
  "id": "f43",
  "name": "Shrimp",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw",
  "calories": 85.0,
  "protein": 20.1,
  "totalCarbs": 0.2,
  "fiber": 0.0,
  "netCarbs": 0.2,
  "fat": 0.5,
  "rating": "Free"
 },
 {
  "id": "f44",
  "name": "Crab",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw",
  "calories": 87.0,
  "protein": 18.1,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 1.1,
  "rating": "Free"
 },
 {
  "id": "f45",
  "name": "Scallops",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw; slight natural carbs",
  "calories": 69.0,
  "protein": 12.1,
  "totalCarbs": 3.2,
  "fiber": 0.0,
  "netCarbs": 3.2,
  "fat": 0.5,
  "rating": "Great"
 },
 {
  "id": "f46",
  "name": "Mussels",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw; watch portions (carbs)",
  "calories": 86.0,
  "protein": 11.9,
  "totalCarbs": 3.7,
  "fiber": 0.0,
  "netCarbs": 3.7,
  "fat": 2.2,
  "rating": "Great"
 },
 {
  "id": "f47",
  "name": "Oysters",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw; watch portions (carbs)",
  "calories": 68.0,
  "protein": 7.0,
  "totalCarbs": 3.9,
  "fiber": 0.0,
  "netCarbs": 3.9,
  "fat": 2.5,
  "rating": "Great"
 },
 {
  "id": "f48",
  "name": "Squid (calamari)",
  "brand": "",
  "category": "Seafood",
  "notes": "Raw; skip breaded versions",
  "calories": 92.0,
  "protein": 15.6,
  "totalCarbs": 3.1,
  "fiber": 0.0,
  "netCarbs": 3.1,
  "fat": 1.4,
  "rating": "Great"
 },
 {
  "id": "f49",
  "name": "Egg, whole",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "Raw; 1 large egg = 50 g",
  "calories": 143.0,
  "protein": 12.6,
  "totalCarbs": 0.7,
  "fiber": 0.0,
  "netCarbs": 0.7,
  "fat": 9.5,
  "rating": "Free"
 },
 {
  "id": "f50",
  "name": "Egg yolk",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "Raw; where the fat & vitamins are",
  "calories": 322.0,
  "protein": 15.9,
  "totalCarbs": 3.6,
  "fiber": 0.0,
  "netCarbs": 3.6,
  "fat": 26.5,
  "rating": "Great"
 },
 {
  "id": "f51",
  "name": "Egg white",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "Raw; almost pure protein",
  "calories": 52.0,
  "protein": 10.9,
  "totalCarbs": 0.7,
  "fiber": 0.0,
  "netCarbs": 0.7,
  "fat": 0.2,
  "rating": "Free"
 },
 {
  "id": "f52",
  "name": "Butter",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "Salted or unsalted",
  "calories": 717.0,
  "protein": 0.9,
  "totalCarbs": 0.1,
  "fiber": 0.0,
  "netCarbs": 0.1,
  "fat": 81.1,
  "rating": "Free"
 },
 {
  "id": "f53",
  "name": "Heavy cream (36%)",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "For coffee, sauces, whipping",
  "calories": 340.0,
  "protein": 2.8,
  "totalCarbs": 2.7,
  "fiber": 0.0,
  "netCarbs": 2.7,
  "fat": 36.1,
  "rating": "Great"
 },
 {
  "id": "f54",
  "name": "Cream cheese, full fat",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "",
  "calories": 342.0,
  "protein": 6.0,
  "totalCarbs": 4.1,
  "fiber": 0.0,
  "netCarbs": 4.1,
  "fat": 34.0,
  "rating": "Great"
 },
 {
  "id": "f55",
  "name": "Cheddar cheese",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "",
  "calories": 404.0,
  "protein": 22.9,
  "totalCarbs": 3.1,
  "fiber": 0.0,
  "netCarbs": 3.1,
  "fat": 33.3,
  "rating": "Great"
 },
 {
  "id": "f56",
  "name": "Mozzarella, whole milk",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "",
  "calories": 300.0,
  "protein": 22.2,
  "totalCarbs": 2.2,
  "fiber": 0.0,
  "netCarbs": 2.2,
  "fat": 22.4,
  "rating": "Great"
 },
 {
  "id": "f57",
  "name": "Parmesan, grated",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "",
  "calories": 420.0,
  "protein": 35.8,
  "totalCarbs": 3.5,
  "fiber": 0.0,
  "netCarbs": 3.5,
  "fat": 27.8,
  "rating": "Great"
 },
 {
  "id": "f58",
  "name": "Brie",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "",
  "calories": 334.0,
  "protein": 20.8,
  "totalCarbs": 0.5,
  "fiber": 0.0,
  "netCarbs": 0.5,
  "fat": 27.7,
  "rating": "Free"
 },
 {
  "id": "f59",
  "name": "Blue cheese",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "",
  "calories": 353.0,
  "protein": 21.4,
  "totalCarbs": 2.3,
  "fiber": 0.0,
  "netCarbs": 2.3,
  "fat": 28.7,
  "rating": "Great"
 },
 {
  "id": "f60",
  "name": "Feta",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "",
  "calories": 264.0,
  "protein": 14.2,
  "totalCarbs": 4.1,
  "fiber": 0.0,
  "netCarbs": 4.1,
  "fat": 21.3,
  "rating": "Great"
 },
 {
  "id": "f61",
  "name": "Goat cheese, soft",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "",
  "calories": 264.0,
  "protein": 18.5,
  "totalCarbs": 0.1,
  "fiber": 0.0,
  "netCarbs": 0.1,
  "fat": 21.1,
  "rating": "Free"
 },
 {
  "id": "f62",
  "name": "Mascarpone",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "Great for keto desserts",
  "calories": 429.0,
  "protein": 4.6,
  "totalCarbs": 4.8,
  "fiber": 0.0,
  "netCarbs": 4.8,
  "fat": 44.0,
  "rating": "Great"
 },
 {
  "id": "f63",
  "name": "Cottage cheese, full fat (4%)",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "Watch portions - has lactose",
  "calories": 98.0,
  "protein": 11.1,
  "totalCarbs": 3.4,
  "fiber": 0.0,
  "netCarbs": 3.4,
  "fat": 4.3,
  "rating": "Great"
 },
 {
  "id": "f64",
  "name": "Sour cream, full fat",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "",
  "calories": 198.0,
  "protein": 2.4,
  "totalCarbs": 4.6,
  "fiber": 0.0,
  "netCarbs": 4.6,
  "fat": 19.4,
  "rating": "Great"
 },
 {
  "id": "f65",
  "name": "Greek yogurt, plain full fat",
  "brand": "",
  "category": "Eggs & Dairy",
  "notes": "Unsweetened only; watch portions",
  "calories": 97.0,
  "protein": 9.0,
  "totalCarbs": 3.9,
  "fiber": 0.0,
  "netCarbs": 3.9,
  "fat": 5.0,
  "rating": "Great"
 },
 {
  "id": "f66",
  "name": "Spinach",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 23.0,
  "protein": 2.9,
  "totalCarbs": 3.6,
  "fiber": 2.2,
  "netCarbs": 1.4,
  "fat": 0.4,
  "rating": "Free"
 },
 {
  "id": "f67",
  "name": "Lettuce, romaine",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 17.0,
  "protein": 1.2,
  "totalCarbs": 3.3,
  "fiber": 2.1,
  "netCarbs": 1.2,
  "fat": 0.3,
  "rating": "Free"
 },
 {
  "id": "f68",
  "name": "Arugula",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 25.0,
  "protein": 2.6,
  "totalCarbs": 3.7,
  "fiber": 1.6,
  "netCarbs": 2.1,
  "fat": 0.7,
  "rating": "Great"
 },
 {
  "id": "f69",
  "name": "Kale",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 35.0,
  "protein": 2.9,
  "totalCarbs": 4.4,
  "fiber": 4.1,
  "netCarbs": 0.3,
  "fat": 1.5,
  "rating": "Free"
 },
 {
  "id": "f70",
  "name": "Swiss chard",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 19.0,
  "protein": 1.8,
  "totalCarbs": 3.7,
  "fiber": 1.6,
  "netCarbs": 2.1,
  "fat": 0.2,
  "rating": "Great"
 },
 {
  "id": "f71",
  "name": "Zucchini",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw; great noodle substitute",
  "calories": 17.0,
  "protein": 1.2,
  "totalCarbs": 3.1,
  "fiber": 1.0,
  "netCarbs": 2.1,
  "fat": 0.3,
  "rating": "Great"
 },
 {
  "id": "f72",
  "name": "Cucumber",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw, with peel",
  "calories": 15.0,
  "protein": 0.7,
  "totalCarbs": 3.6,
  "fiber": 0.5,
  "netCarbs": 3.1,
  "fat": 0.1,
  "rating": "Great"
 },
 {
  "id": "f73",
  "name": "Celery",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 14.0,
  "protein": 0.7,
  "totalCarbs": 3.0,
  "fiber": 1.6,
  "netCarbs": 1.4,
  "fat": 0.2,
  "rating": "Free"
 },
 {
  "id": "f74",
  "name": "Radish",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 16.0,
  "protein": 0.7,
  "totalCarbs": 3.4,
  "fiber": 1.6,
  "netCarbs": 1.8,
  "fat": 0.1,
  "rating": "Free"
 },
 {
  "id": "f75",
  "name": "Asparagus",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 20.0,
  "protein": 2.2,
  "totalCarbs": 3.9,
  "fiber": 2.1,
  "netCarbs": 1.8,
  "fat": 0.1,
  "rating": "Free"
 },
 {
  "id": "f76",
  "name": "Mushrooms, white",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 22.0,
  "protein": 3.1,
  "totalCarbs": 3.3,
  "fiber": 1.0,
  "netCarbs": 2.3,
  "fat": 0.3,
  "rating": "Great"
 },
 {
  "id": "f77",
  "name": "Cauliflower",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw; rice & mash substitute",
  "calories": 25.0,
  "protein": 1.9,
  "totalCarbs": 5.0,
  "fiber": 2.0,
  "netCarbs": 3.0,
  "fat": 0.3,
  "rating": "Great"
 },
 {
  "id": "f78",
  "name": "Broccoli",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 34.0,
  "protein": 2.8,
  "totalCarbs": 6.6,
  "fiber": 2.6,
  "netCarbs": 4.0,
  "fat": 0.4,
  "rating": "Great"
 },
 {
  "id": "f79",
  "name": "Cabbage",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 25.0,
  "protein": 1.3,
  "totalCarbs": 5.8,
  "fiber": 2.5,
  "netCarbs": 3.3,
  "fat": 0.1,
  "rating": "Great"
 },
 {
  "id": "f80",
  "name": "Eggplant",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 25.0,
  "protein": 1.0,
  "totalCarbs": 5.9,
  "fiber": 3.0,
  "netCarbs": 2.9,
  "fat": 0.2,
  "rating": "Great"
 },
 {
  "id": "f81",
  "name": "Tomato",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 18.0,
  "protein": 0.9,
  "totalCarbs": 3.9,
  "fiber": 1.2,
  "netCarbs": 2.7,
  "fat": 0.2,
  "rating": "Great"
 },
 {
  "id": "f82",
  "name": "Bell pepper, green",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw; lowest-carb color",
  "calories": 20.0,
  "protein": 0.9,
  "totalCarbs": 4.6,
  "fiber": 1.7,
  "netCarbs": 2.9,
  "fat": 0.2,
  "rating": "Great"
 },
 {
  "id": "f83",
  "name": "Bell pepper, red",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw",
  "calories": 31.0,
  "protein": 1.0,
  "totalCarbs": 6.0,
  "fiber": 2.1,
  "netCarbs": 3.9,
  "fat": 0.3,
  "rating": "Great"
 },
 {
  "id": "f84",
  "name": "Green beans",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw; watch portions",
  "calories": 31.0,
  "protein": 1.8,
  "totalCarbs": 7.0,
  "fiber": 2.7,
  "netCarbs": 4.3,
  "fat": 0.2,
  "rating": "Great"
 },
 {
  "id": "f85",
  "name": "Brussels sprouts",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw; watch portions",
  "calories": 43.0,
  "protein": 3.4,
  "totalCarbs": 9.0,
  "fiber": 3.8,
  "netCarbs": 5.2,
  "fat": 0.3,
  "rating": "Moderate"
 },
 {
  "id": "f86",
  "name": "Onion",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw; use small amounts for flavor",
  "calories": 40.0,
  "protein": 1.1,
  "totalCarbs": 9.3,
  "fiber": 1.7,
  "netCarbs": 7.6,
  "fat": 0.1,
  "rating": "Moderate"
 },
 {
  "id": "f87",
  "name": "Garlic",
  "brand": "",
  "category": "Vegetables",
  "notes": "Raw; 1 clove = 3 g (~1 g net carbs)",
  "calories": 149.0,
  "protein": 6.4,
  "totalCarbs": 33.1,
  "fiber": 2.1,
  "netCarbs": 31.0,
  "fat": 0.5,
  "rating": "Portion Control"
 },
 {
  "id": "f88",
  "name": "Olives, green",
  "brand": "",
  "category": "Vegetables",
  "notes": "In brine",
  "calories": 145.0,
  "protein": 1.0,
  "totalCarbs": 3.8,
  "fiber": 3.3,
  "netCarbs": 0.5,
  "fat": 15.3,
  "rating": "Free"
 },
 {
  "id": "f89",
  "name": "Sauerkraut",
  "brand": "",
  "category": "Vegetables",
  "notes": "Fermented; check label for sugar",
  "calories": 19.0,
  "protein": 0.9,
  "totalCarbs": 4.3,
  "fiber": 2.9,
  "netCarbs": 1.4,
  "fat": 0.1,
  "rating": "Free"
 },
 {
  "id": "f90",
  "name": "Avocado",
  "brand": "",
  "category": "Fruits",
  "notes": "The #1 keto fruit",
  "calories": 160.0,
  "protein": 2.0,
  "totalCarbs": 8.5,
  "fiber": 6.7,
  "netCarbs": 1.8,
  "fat": 14.7,
  "rating": "Free"
 },
 {
  "id": "f91",
  "name": "Blackberries",
  "brand": "",
  "category": "Fruits",
  "notes": "Lowest-carb berry",
  "calories": 43.0,
  "protein": 1.4,
  "totalCarbs": 9.6,
  "fiber": 5.3,
  "netCarbs": 4.3,
  "fat": 0.5,
  "rating": "Great"
 },
 {
  "id": "f92",
  "name": "Raspberries",
  "brand": "",
  "category": "Fruits",
  "notes": "",
  "calories": 52.0,
  "protein": 1.2,
  "totalCarbs": 11.9,
  "fiber": 6.5,
  "netCarbs": 5.4,
  "fat": 0.7,
  "rating": "Moderate"
 },
 {
  "id": "f93",
  "name": "Strawberries",
  "brand": "",
  "category": "Fruits",
  "notes": "Watch portions",
  "calories": 32.0,
  "protein": 0.7,
  "totalCarbs": 7.7,
  "fiber": 2.0,
  "netCarbs": 5.7,
  "fat": 0.3,
  "rating": "Moderate"
 },
 {
  "id": "f94",
  "name": "Blueberries",
  "brand": "",
  "category": "Fruits",
  "notes": "Small portions only",
  "calories": 57.0,
  "protein": 0.7,
  "totalCarbs": 14.5,
  "fiber": 2.4,
  "netCarbs": 12.1,
  "fat": 0.3,
  "rating": "Portion Control"
 },
 {
  "id": "f95",
  "name": "Lemon",
  "brand": "",
  "category": "Fruits",
  "notes": "Mostly used as juice/zest",
  "calories": 29.0,
  "protein": 1.1,
  "totalCarbs": 9.3,
  "fiber": 2.8,
  "netCarbs": 6.5,
  "fat": 0.3,
  "rating": "Moderate"
 },
 {
  "id": "f96",
  "name": "Lime",
  "brand": "",
  "category": "Fruits",
  "notes": "Mostly used as juice/zest",
  "calories": 30.0,
  "protein": 0.7,
  "totalCarbs": 10.5,
  "fiber": 2.8,
  "netCarbs": 7.7,
  "fat": 0.2,
  "rating": "Moderate"
 },
 {
  "id": "f97",
  "name": "Coconut meat, fresh",
  "brand": "",
  "category": "Fruits",
  "notes": "",
  "calories": 354.0,
  "protein": 3.3,
  "totalCarbs": 15.2,
  "fiber": 9.0,
  "netCarbs": 6.2,
  "fat": 33.5,
  "rating": "Moderate"
 },
 {
  "id": "f98",
  "name": "Macadamia nuts",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "Lowest-carb, highest-fat nut",
  "calories": 718.0,
  "protein": 7.9,
  "totalCarbs": 13.8,
  "fiber": 8.6,
  "netCarbs": 5.2,
  "fat": 75.8,
  "rating": "Moderate"
 },
 {
  "id": "f99",
  "name": "Pecans",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "",
  "calories": 691.0,
  "protein": 9.2,
  "totalCarbs": 13.9,
  "fiber": 9.6,
  "netCarbs": 4.3,
  "fat": 72.0,
  "rating": "Great"
 },
 {
  "id": "f100",
  "name": "Brazil nuts",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "Selenium-rich; 1-3 per day is plenty",
  "calories": 659.0,
  "protein": 14.3,
  "totalCarbs": 11.7,
  "fiber": 7.5,
  "netCarbs": 4.2,
  "fat": 67.1,
  "rating": "Great"
 },
 {
  "id": "f101",
  "name": "Walnuts",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "",
  "calories": 654.0,
  "protein": 15.2,
  "totalCarbs": 13.7,
  "fiber": 6.7,
  "netCarbs": 7.0,
  "fat": 65.2,
  "rating": "Moderate"
 },
 {
  "id": "f102",
  "name": "Hazelnuts",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "",
  "calories": 628.0,
  "protein": 15.0,
  "totalCarbs": 16.7,
  "fiber": 9.7,
  "netCarbs": 7.0,
  "fat": 60.8,
  "rating": "Moderate"
 },
 {
  "id": "f103",
  "name": "Almonds",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "",
  "calories": 579.0,
  "protein": 21.2,
  "totalCarbs": 21.6,
  "fiber": 12.5,
  "netCarbs": 9.1,
  "fat": 49.9,
  "rating": "Moderate"
 },
 {
  "id": "f104",
  "name": "Peanuts",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "Technically a legume; fine in moderation",
  "calories": 567.0,
  "protein": 25.8,
  "totalCarbs": 16.1,
  "fiber": 8.5,
  "netCarbs": 7.6,
  "fat": 49.2,
  "rating": "Moderate"
 },
 {
  "id": "f105",
  "name": "Pistachios",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "Higher carb - watch portions",
  "calories": 560.0,
  "protein": 20.2,
  "totalCarbs": 27.2,
  "fiber": 10.6,
  "netCarbs": 16.6,
  "fat": 45.3,
  "rating": "Portion Control"
 },
 {
  "id": "f106",
  "name": "Cashews",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "Highest-carb nut - small portions only",
  "calories": 553.0,
  "protein": 18.2,
  "totalCarbs": 30.2,
  "fiber": 3.3,
  "netCarbs": 26.9,
  "fat": 43.8,
  "rating": "Portion Control"
 },
 {
  "id": "f107",
  "name": "Chia seeds",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "Almost all carbs are fiber",
  "calories": 486.0,
  "protein": 16.5,
  "totalCarbs": 42.1,
  "fiber": 34.4,
  "netCarbs": 7.7,
  "fat": 30.7,
  "rating": "Moderate"
 },
 {
  "id": "f108",
  "name": "Flaxseed / flax meal",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "Almost all carbs are fiber",
  "calories": 534.0,
  "protein": 18.3,
  "totalCarbs": 28.9,
  "fiber": 27.3,
  "netCarbs": 1.6,
  "fat": 42.2,
  "rating": "Free"
 },
 {
  "id": "f109",
  "name": "Hemp seeds (hearts)",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "Very keto-friendly",
  "calories": 553.0,
  "protein": 31.6,
  "totalCarbs": 8.7,
  "fiber": 4.0,
  "netCarbs": 4.7,
  "fat": 48.8,
  "rating": "Great"
 },
 {
  "id": "f110",
  "name": "Pumpkin seeds (pepitas)",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "",
  "calories": 559.0,
  "protein": 30.2,
  "totalCarbs": 10.7,
  "fiber": 6.0,
  "netCarbs": 4.7,
  "fat": 49.1,
  "rating": "Great"
 },
 {
  "id": "f111",
  "name": "Sunflower seeds",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "",
  "calories": 584.0,
  "protein": 20.8,
  "totalCarbs": 20.0,
  "fiber": 8.6,
  "netCarbs": 11.4,
  "fat": 51.5,
  "rating": "Portion Control"
 },
 {
  "id": "f112",
  "name": "Sesame seeds / tahini",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "",
  "calories": 573.0,
  "protein": 17.7,
  "totalCarbs": 23.5,
  "fiber": 11.8,
  "netCarbs": 11.7,
  "fat": 49.7,
  "rating": "Portion Control"
 },
 {
  "id": "f113",
  "name": "Almond butter",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "No added sugar",
  "calories": 614.0,
  "protein": 21.0,
  "totalCarbs": 18.8,
  "fiber": 10.3,
  "netCarbs": 8.5,
  "fat": 55.5,
  "rating": "Moderate"
 },
 {
  "id": "f114",
  "name": "Peanut butter, natural",
  "brand": "",
  "category": "Nuts & Seeds",
  "notes": "No added sugar",
  "calories": 588.0,
  "protein": 25.1,
  "totalCarbs": 20.0,
  "fiber": 6.0,
  "netCarbs": 14.0,
  "fat": 50.0,
  "rating": "Portion Control"
 },
 {
  "id": "f115",
  "name": "Olive oil, extra virgin",
  "brand": "",
  "category": "Fats & Oils",
  "notes": "1 tbsp = 14 g / 119 kcal",
  "calories": 884.0,
  "protein": 0.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 100.0,
  "rating": "Free"
 },
 {
  "id": "f116",
  "name": "Avocado oil",
  "brand": "",
  "category": "Fats & Oils",
  "notes": "High smoke point - best for frying",
  "calories": 884.0,
  "protein": 0.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 100.0,
  "rating": "Free"
 },
 {
  "id": "f117",
  "name": "Coconut oil",
  "brand": "",
  "category": "Fats & Oils",
  "notes": "",
  "calories": 862.0,
  "protein": 0.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 100.0,
  "rating": "Free"
 },
 {
  "id": "f118",
  "name": "MCT oil",
  "brand": "",
  "category": "Fats & Oils",
  "notes": "Fast ketone fuel; start with 1 tsp",
  "calories": 855.0,
  "protein": 0.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 100.0,
  "rating": "Free"
 },
 {
  "id": "f119",
  "name": "Ghee (clarified butter)",
  "brand": "",
  "category": "Fats & Oils",
  "notes": "Lactose-free, high smoke point",
  "calories": 876.0,
  "protein": 0.3,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 99.5,
  "rating": "Free"
 },
 {
  "id": "f120",
  "name": "Butter",
  "brand": "",
  "category": "Fats & Oils",
  "notes": "1 tbsp = 14 g / 100 kcal",
  "calories": 717.0,
  "protein": 0.9,
  "totalCarbs": 0.1,
  "fiber": 0.0,
  "netCarbs": 0.1,
  "fat": 81.1,
  "rating": "Free"
 },
 {
  "id": "f121",
  "name": "Lard (pork fat)",
  "brand": "",
  "category": "Fats & Oils",
  "notes": "",
  "calories": 902.0,
  "protein": 0.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 100.0,
  "rating": "Free"
 },
 {
  "id": "f122",
  "name": "Beef tallow",
  "brand": "",
  "category": "Fats & Oils",
  "notes": "",
  "calories": 902.0,
  "protein": 0.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 100.0,
  "rating": "Free"
 },
 {
  "id": "f123",
  "name": "Duck fat",
  "brand": "",
  "category": "Fats & Oils",
  "notes": "",
  "calories": 900.0,
  "protein": 0.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 100.0,
  "rating": "Free"
 },
 {
  "id": "f124",
  "name": "Mayonnaise (avocado oil)",
  "brand": "",
  "category": "Fats & Oils",
  "notes": "Avoid soybean/canola versions",
  "calories": 680.0,
  "protein": 1.0,
  "totalCarbs": 0.6,
  "fiber": 0.0,
  "netCarbs": 0.6,
  "fat": 75.0,
  "rating": "Free"
 },
 {
  "id": "f125",
  "name": "Water / sparkling water",
  "brand": "",
  "category": "Beverages",
  "notes": "Per 100 ml",
  "calories": 0.0,
  "protein": 0.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 0.0,
  "rating": "Free"
 },
 {
  "id": "f126",
  "name": "Coffee, black",
  "brand": "",
  "category": "Beverages",
  "notes": "Per 100 ml",
  "calories": 1.0,
  "protein": 0.1,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 0.0,
  "rating": "Free"
 },
 {
  "id": "f127",
  "name": "Tea, unsweetened",
  "brand": "",
  "category": "Beverages",
  "notes": "Per 100 ml",
  "calories": 1.0,
  "protein": 0.0,
  "totalCarbs": 0.2,
  "fiber": 0.0,
  "netCarbs": 0.2,
  "fat": 0.0,
  "rating": "Free"
 },
 {
  "id": "f128",
  "name": "Almond milk, unsweetened",
  "brand": "",
  "category": "Beverages",
  "notes": "Per 100 ml",
  "calories": 13.0,
  "protein": 0.4,
  "totalCarbs": 0.3,
  "fiber": 0.2,
  "netCarbs": 0.1,
  "fat": 1.1,
  "rating": "Free"
 },
 {
  "id": "f129",
  "name": "Coconut milk, canned full fat",
  "brand": "",
  "category": "Beverages",
  "notes": "Per 100 ml; for cooking & coffee",
  "calories": 197.0,
  "protein": 2.0,
  "totalCarbs": 2.8,
  "fiber": 0.0,
  "netCarbs": 2.8,
  "fat": 21.3,
  "rating": "Great"
 },
 {
  "id": "f130",
  "name": "Bone broth",
  "brand": "",
  "category": "Beverages",
  "notes": "Per 100 ml; good for electrolytes",
  "calories": 17.0,
  "protein": 4.0,
  "totalCarbs": 0.4,
  "fiber": 0.0,
  "netCarbs": 0.4,
  "fat": 0.2,
  "rating": "Free"
 },
 {
  "id": "f131",
  "name": "Electrolyte drink, sugar-free",
  "brand": "",
  "category": "Beverages",
  "notes": "Per 100 ml; check label = 0 sugar",
  "calories": 1.0,
  "protein": 0.0,
  "totalCarbs": 0.2,
  "fiber": 0.0,
  "netCarbs": 0.2,
  "fat": 0.0,
  "rating": "Free"
 },
 {
  "id": "f132",
  "name": "Bulletproof / butter coffee",
  "brand": "",
  "category": "Beverages",
  "notes": "Per cup with 1 tbsp butter + 1 tbsp MCT",
  "calories": 220.0,
  "protein": 0.3,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 25.0,
  "rating": "Free"
 },
 {
  "id": "f133",
  "name": "Mustard, yellow",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 g; ~0.3 g carbs per tsp",
  "calories": 60.0,
  "protein": 3.7,
  "totalCarbs": 5.8,
  "fiber": 4.0,
  "netCarbs": 1.8,
  "fat": 3.3,
  "rating": "Free"
 },
 {
  "id": "f134",
  "name": "Hot sauce",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 g; near zero per serving",
  "calories": 11.0,
  "protein": 0.5,
  "totalCarbs": 1.8,
  "fiber": 0.3,
  "netCarbs": 1.5,
  "fat": 0.4,
  "rating": "Free"
 },
 {
  "id": "f135",
  "name": "Apple cider vinegar",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 ml",
  "calories": 21.0,
  "protein": 0.0,
  "totalCarbs": 0.9,
  "fiber": 0.0,
  "netCarbs": 0.9,
  "fat": 0.0,
  "rating": "Free"
 },
 {
  "id": "f136",
  "name": "Soy sauce / tamari",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 ml; salty - small amounts",
  "calories": 53.0,
  "protein": 8.1,
  "totalCarbs": 4.9,
  "fiber": 0.8,
  "netCarbs": 4.1,
  "fat": 0.6,
  "rating": "Great"
 },
 {
  "id": "f137",
  "name": "Coconut aminos",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 ml; soy sauce substitute",
  "calories": 133.0,
  "protein": 0.0,
  "totalCarbs": 30.0,
  "fiber": 0.0,
  "netCarbs": 30.0,
  "fat": 0.0,
  "rating": "Portion Control"
 },
 {
  "id": "f138",
  "name": "Ketchup, no sugar added",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 g; ~1 g per tbsp",
  "calories": 25.0,
  "protein": 1.0,
  "totalCarbs": 5.0,
  "fiber": 1.0,
  "netCarbs": 4.0,
  "fat": 0.0,
  "rating": "Great"
 },
 {
  "id": "f139",
  "name": "BBQ sauce, no sugar added",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 g; check label carefully",
  "calories": 40.0,
  "protein": 1.0,
  "totalCarbs": 8.0,
  "fiber": 2.0,
  "netCarbs": 6.0,
  "fat": 0.5,
  "rating": "Moderate"
 },
 {
  "id": "f140",
  "name": "Pesto",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 g; check for added sugar",
  "calories": 450.0,
  "protein": 5.0,
  "totalCarbs": 6.0,
  "fiber": 2.0,
  "netCarbs": 4.0,
  "fat": 45.0,
  "rating": "Great"
 },
 {
  "id": "f141",
  "name": "Guacamole",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 g",
  "calories": 155.0,
  "protein": 2.0,
  "totalCarbs": 8.0,
  "fiber": 6.0,
  "netCarbs": 2.0,
  "fat": 14.0,
  "rating": "Free"
 },
 {
  "id": "f142",
  "name": "Erythritol",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 g; ~0 kcal, carbs not absorbed",
  "calories": 20.0,
  "protein": 0.0,
  "totalCarbs": 100.0,
  "fiber": 100.0,
  "netCarbs": 0.0,
  "fat": 0.0,
  "rating": "Free"
 },
 {
  "id": "f143",
  "name": "Monk fruit sweetener",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 g; usually blended w/ erythritol",
  "calories": 0.0,
  "protein": 0.0,
  "totalCarbs": 100.0,
  "fiber": 100.0,
  "netCarbs": 0.0,
  "fat": 0.0,
  "rating": "Free"
 },
 {
  "id": "f144",
  "name": "Stevia",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 g; use drops or pure powder",
  "calories": 0.0,
  "protein": 0.0,
  "totalCarbs": 100.0,
  "fiber": 100.0,
  "netCarbs": 0.0,
  "fat": 0.0,
  "rating": "Free"
 },
 {
  "id": "f145",
  "name": "Allulose",
  "brand": "",
  "category": "Condiments & Sweeteners",
  "notes": "Per 100 g; rare sugar, not metabolized",
  "calories": 40.0,
  "protein": 0.0,
  "totalCarbs": 100.0,
  "fiber": 100.0,
  "netCarbs": 0.0,
  "fat": 0.0,
  "rating": "Free"
 },
 {
  "id": "f146",
  "name": "Almond flour",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "Main keto flour",
  "calories": 590.0,
  "protein": 21.4,
  "totalCarbs": 21.4,
  "fiber": 10.7,
  "netCarbs": 10.7,
  "fat": 53.6,
  "rating": "Portion Control"
 },
 {
  "id": "f147",
  "name": "Coconut flour",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "Very absorbent - use 1/4 the amount",
  "calories": 429.0,
  "protein": 19.3,
  "totalCarbs": 57.1,
  "fiber": 35.7,
  "netCarbs": 21.4,
  "fat": 14.3,
  "rating": "Portion Control"
 },
 {
  "id": "f148",
  "name": "Flaxseed meal",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "Egg substitute & baking",
  "calories": 534.0,
  "protein": 18.3,
  "totalCarbs": 28.9,
  "fiber": 27.3,
  "netCarbs": 1.6,
  "fat": 42.2,
  "rating": "Free"
 },
 {
  "id": "f149",
  "name": "Psyllium husk",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "Gives keto bread its texture",
  "calories": 210.0,
  "protein": 1.5,
  "totalCarbs": 88.0,
  "fiber": 85.0,
  "netCarbs": 3.0,
  "fat": 0.6,
  "rating": "Great"
 },
 {
  "id": "f150",
  "name": "Cocoa powder, unsweetened",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "",
  "calories": 228.0,
  "protein": 19.6,
  "totalCarbs": 57.9,
  "fiber": 37.0,
  "netCarbs": 20.9,
  "fat": 13.7,
  "rating": "Portion Control"
 },
 {
  "id": "f151",
  "name": "Dark chocolate 85%+",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "1 square (~10 g) = ~1.5 g net carbs",
  "calories": 590.0,
  "protein": 9.8,
  "totalCarbs": 24.0,
  "fiber": 12.0,
  "netCarbs": 12.0,
  "fat": 53.0,
  "rating": "Portion Control"
 },
 {
  "id": "f152",
  "name": "Baking powder",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "Trace amounts per recipe",
  "calories": 53.0,
  "protein": 0.0,
  "totalCarbs": 27.7,
  "fiber": 0.2,
  "netCarbs": 27.5,
  "fat": 0.0,
  "rating": "Portion Control"
 },
 {
  "id": "f153",
  "name": "Shirataki noodles / rice (konjac)",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "Nearly zero everything",
  "calories": 7.0,
  "protein": 0.0,
  "totalCarbs": 3.0,
  "fiber": 3.0,
  "netCarbs": 0.0,
  "fat": 0.0,
  "rating": "Free"
 },
 {
  "id": "f154",
  "name": "Canned sardines",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "Zero-carb protein staple",
  "calories": 208.0,
  "protein": 24.6,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 11.4,
  "rating": "Free"
 },
 {
  "id": "f155",
  "name": "Canned chicken breast",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "Drained",
  "calories": 105.0,
  "protein": 22.0,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 1.5,
  "rating": "Free"
 },
 {
  "id": "f156",
  "name": "Canned tomatoes, no sugar",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "Watch portions",
  "calories": 18.0,
  "protein": 0.9,
  "totalCarbs": 3.9,
  "fiber": 1.2,
  "netCarbs": 2.7,
  "fat": 0.2,
  "rating": "Great"
 },
 {
  "id": "f157",
  "name": "Herbs & spices (avg)",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "~1 g net carbs per tsp - negligible",
  "calories": 280.0,
  "protein": 10.0,
  "totalCarbs": 55.0,
  "fiber": 25.0,
  "netCarbs": 30.0,
  "fat": 6.0,
  "rating": "Portion Control"
 },
 {
  "id": "f158",
  "name": "Pork rind breadcrumbs",
  "brand": "",
  "category": "Pantry & Baking",
  "notes": "Zero-carb breading",
  "calories": 544.0,
  "protein": 61.3,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 31.3,
  "rating": "Free"
 },
 {
  "id": "f159",
  "name": "Pork rinds (chicharrones)",
  "brand": "",
  "category": "Snacks",
  "notes": "Zero carb",
  "calories": 544.0,
  "protein": 61.3,
  "totalCarbs": 0.0,
  "fiber": 0.0,
  "netCarbs": 0.0,
  "fat": 31.3,
  "rating": "Free"
 },
 {
  "id": "f160",
  "name": "Beef jerky, sugar-free",
  "brand": "",
  "category": "Snacks",
  "notes": "Check label - most brands add sugar",
  "calories": 330.0,
  "protein": 40.0,
  "totalCarbs": 3.0,
  "fiber": 0.0,
  "netCarbs": 3.0,
  "fat": 17.0,
  "rating": "Great"
 },
 {
  "id": "f161",
  "name": "Hard-boiled egg",
  "brand": "",
  "category": "Snacks",
  "notes": "1 large egg = 50 g",
  "calories": 155.0,
  "protein": 12.6,
  "totalCarbs": 1.1,
  "fiber": 0.0,
  "netCarbs": 1.1,
  "fat": 10.6,
  "rating": "Free"
 },
 {
  "id": "f162",
  "name": "Cheese crisps / sliced cheese",
  "brand": "",
  "category": "Snacks",
  "notes": "",
  "calories": 404.0,
  "protein": 22.9,
  "totalCarbs": 3.1,
  "fiber": 0.0,
  "netCarbs": 3.1,
  "fat": 33.3,
  "rating": "Great"
 },
 {
  "id": "f163",
  "name": "Dried seaweed snacks",
  "brand": "",
  "category": "Snacks",
  "notes": "Per 100 g; one pack is ~5 g",
  "calories": 350.0,
  "protein": 30.0,
  "totalCarbs": 40.0,
  "fiber": 25.0,
  "netCarbs": 15.0,
  "fat": 5.0,
  "rating": "Portion Control"
 },
 {
  "id": "f164",
  "name": "Olives",
  "brand": "",
  "category": "Snacks",
  "notes": "",
  "calories": 145.0,
  "protein": 1.0,
  "totalCarbs": 3.8,
  "fiber": 3.3,
  "netCarbs": 0.5,
  "fat": 15.3,
  "rating": "Free"
 },
 {
  "id": "f165",
  "name": "Pepperoni slices",
  "brand": "",
  "category": "Snacks",
  "notes": "",
  "calories": 460.0,
  "protein": 20.0,
  "totalCarbs": 1.5,
  "fiber": 0.0,
  "netCarbs": 1.5,
  "fat": 41.0,
  "rating": "Free"
 },
 {
  "id": "f166",
  "name": "Macadamia nuts",
  "brand": "",
  "category": "Snacks",
  "notes": "",
  "calories": 718.0,
  "protein": 7.9,
  "totalCarbs": 13.8,
  "fiber": 8.6,
  "netCarbs": 5.2,
  "fat": 75.8,
  "rating": "Moderate"
 },
 {
  "id": "f167",
  "name": "Celery + almond butter",
  "brand": "",
  "category": "Snacks",
  "notes": "Per 100 g combined (50/50)",
  "calories": 314.0,
  "protein": 10.9,
  "totalCarbs": 10.9,
  "fiber": 6.0,
  "netCarbs": 4.9,
  "fat": 27.9,
  "rating": "Great"
 },
 {
  "id": "f168",
  "name": "Fat bombs (homemade)",
  "brand": "",
  "category": "Snacks",
  "notes": "Varies by recipe; typically <1 g net carb",
  "calories": 550.0,
  "protein": 3.0,
  "totalCarbs": 6.0,
  "fiber": 3.0,
  "netCarbs": 3.0,
  "fat": 57.0,
  "rating": "Great"
 }
];
